#!/usr/bin/env bash
#script that will display information about subdomains
if [ "$#" -lt 1 ];
    then
        dig www.joeldumortier.tech | grep -A1 'ANSWER SECTION' | tail -n +2 | awk '{print "The subdomain www is a " $4 " record and points to "$5}';
        dig lb-01.joeldumortier.tech | grep -A1 'ANSWER SECTION' | tail -n +2 | awk '{print "The subdomain lb-01 is a " $4 " record and points to "$5}';
        dig web-01.joeldumortier.tech | grep -A1 'ANSWER SECTION' | tail -n +2 | awk '{print "The subdomain web-01 is a " $4 " record and points to "$5}';
        dig web-02.joeldumortier.tech | grep -A1 'ANSWER SECTION' | tail -n +2 | awk '{print "The subdomain web-02 is a " $4 " record and points to "$5}';
    else
        SUB=$1
        dig "$1".joeldumortier.tech | grep -A1 'ANSWER SECTION' | tail -n +2 | awk -v s="$SUB" '{print "The subdomain "s " is a " $4 " record and points to "$5}';
fi