#!/usr/bin/env bash
# configures Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
bash -c 'echo Hello World > /var/www/html/index.nginx-debian.html'
sed -i '/^\s*server_name \_\;$/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx restart