#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo bash -c 'echo Hello World > /var/www/html/index.nginx-debian.html'
sudo sed -i "/^\s*location \/ {$/a add_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default
sudo service nginx restart