#!/usr/bin/env bash
#script that generates a MySQL dump and creates a compressed archive out of it

TODAY=$(date +"%d-%m-%Y")

MYSQL_USER="root"
MYSQL_PASSWORD=$1

mysqldump --user "$MYSQL_USER" --password "$MYSQL_PASSWORD" --all-databases > backup.sql;
tar -cvzf "$TODAY.tar.gz" backup.sql;
