#!/usr/bin/env bash
#script that fix bug
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ln -s -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart