#!/usr/bin/env bash
# script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/my.pid
function handlesig()
{
    echo "I hate the kill command"
    rm -f /var/run/my.pid
    exit
}
while 'true'
do
        echo "To infinity and beyond"
        sleep 2
        trap "echo Y U no love me?!" 2
        trap handlesig 3 15
done        