#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
MIN=1
HOUR=0
while [ $HOUR -lt 13 ];
do
        echo "Hour: "$HOUR
        while [ $MIN -lt 60 ]
        do
                echo $MIN
                MIN=$((MIN+1))
        done
        HOUR=$((HOUR+1))
        MIN=1
done
