#!/usr/bin/env bash
# script that Fix this container so that Nginx is running as the nginx user
pkill apache2
sed -i 's/80/8080' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
