#!/usr/bin/env bash
# script that Fix this container so that Nginx is running as the nginx user
pkill apache2
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 660 /etc/nginx/nginx.conf
sed -i 's/80/8080' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
